---
  - hosts: SAS_Test
    connection: local
    tasks:
      - name: go into enable mode
        staging_ios:
          obm_ipv4: 10.65.0.50
          port: 3010
          username: root
          password:  GDTlabs123
          command: enable
          enable: False
      - debug: var=enable
